### PR TITLE
Fix compile with opus-1.3.1 and emscripten-2.0.17

### PR DESCRIPTION
**Pull request by chrbsg**
- Use latest stable upstream opus-1.3.1.

- Disable default build options not supported by emscripten
  (--disable-stack-protector --disable-hardening).

- Fix runtime error `_free is not a function`.
  Emscripten no longer exports _free by default, so explicitly export it.

### CODE REVIEW

**Comment by ImagicTheCat** [comment]
Thanks.
